import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Layout from '@/components/elements/Layout'
import Navbar from '@/components/elements/Navbar'
import Footer from '@/components/elements/Footer'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Layout>
          <Navbar />
          {children}
          <Footer />
        </Layout>
      </body>
    </html>
  )
}
